CREATE TABLE paginas(Id INT, title text, description text, keywords text, url text);INSERT INTO paginas(Id, title, description, keywords, url) VALUES(1,'Yahoo Australia | News, email and search','Latest news, email and search are just the beginning. Discover more every day.','yahoo, yahoo home page, yahoo homepage, yahoo search, yahoo mail, yahoo messenger, yahoo games, news, finance, sport, entertainment','http://au.messages.yahoo.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(2,'Sky - Discover TV, Broadband & Mobile packages | Sky.com','Discover Sky packages on TV, broadband & mobile including Glass - the new streaming TV with Sky Inside. Login & manage your My Sky account & more.','Sky Glass, Glass TV, Sky, Sky TV, Sky Broadband, Sky Fibre, Sky Mobile, Sky Entertainment, Sky Sports, Sky Cinema','http://www.sky.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(3,'Build a Free Website with Web Hosting | Tripod','Build a free website with our easy to use, free website builder.  Find web hosting, domain registration, email and more at Tripod.com.','free website, web hosting, website hosting, website templates, tripod','http://members.tripod.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(4,'CreateBlog: Myspace Layouts, Hi5 Layouts, Friendster Layouts, Xanga Layouts, Myspace Tracker','Grab Myspace layouts and codes, Myspace tracker, Myspace backgrounds, Xanga layouts, Hi5 layouts, Friendster layouts and more!','Myspace Layouts, Myspace Tracker, Myspace Codes, Hi5 Layouts, Friendster Layouts, Xanga Layouts','http://www.createblog.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(5,'Featured Content on Myspace','Featured Content on Myspace','Myspace, social entertainment, artist tools, social media, social discovery, creative community, empowering expression, stream music, music videos, music, share music, playlists, mixes, profiles, discovery, discover','http://www.myspace.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(6,'Outside of Ordinary | Alfred University','What do Tesla, the Navy Seals, Apple and Meals on Wheels have in common? Alfred University graduates work there, among other crazy smart companies.','Alfred, Alfred University, AU, alfred college','http://www.alfred.edu');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(7,'SOUNDTRACK LYRICS - STLyrics.com','Soundtrack lyrics for any movie, cartoon, TV, game, Broadway musical. Browse song by artist or soundtrack title.','lyrics, sound track, song, soundtrack, soundtrack lyrics, movie, cartoon, tv, musical, game, film','http://www.stlyrics.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(8,'** SpoilerFix.com **','','','http://www.spoilerfix.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(9,'96.5 KISS-FM - Cleveland's #1 Hit Music Station','Cleveland's #1 Hit Music Station ','kiss fm, cleveland, 96.5, 96-5, top 40, kiss','http://www.965kissfm.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(10,'96.5 KISS-FM - Cleveland's #1 Hit Music Station','Cleveland's #1 Hit Music Station ','kiss fm, cleveland, 96.5, 96-5, top 40, kiss','http://www.kissfm965.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(11,'96.5 KISS-FM - Cleveland's #1 Hit Music Station','Cleveland's #1 Hit Music Station ','kiss fm, cleveland, 96.5, 96-5, top 40, kiss','http://www.kisscleveland.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(12,'Absolute Shakespeare - plays, quotes, summaries, essays...','Absolute Shakespeare, the essential resource for for William Shakespeares plays, sonnets, poems, quotes, biography and the legendary Globe Theatre.','william shakespeare immortal bard Shakespeare play sonnet essays quote poem plays shakspear sonnets charactersbiography essay timeline globe theatre paintings picture film facts authorship debate ','http://absoluteshakespeare.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(13,'WILLIAM SHAKESPEARE','Visit this site dedicated to the playwright William Shakespeare and his famous works. William Shakespeare plays like Hamlet, Othello, King Lear, Macbeth and the Tempest. William Shakespeares Sonnets and Pictures are featured as well as his poems and biography.','william,shakespeare,play,sonnet,plays,sonnets,shakespear,pictures,poems,tempest,king lear,macbeth,othello,hamlet,biography,elizabethan,globe,theatre','http://www.william-shakespeare.info');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(14,'Cleveland, OH - Real Estate * a comprehensive resource','Cleveland, Ohio Real Estate - a 
comprehensive resource forreal estate information in general and/or Cleveland 
and surrounding areas specifically. Includesfree classifieds for real estate 
sales.','Cleveland,Ohio,Real
Estate,classifieds,maps,pictures,photos,employment,escrow,title,company,examiner
,lender,mortgage,bank,attorney,realtor,Cleveland,Ohio,news,software','http://www.cleve-oh.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(15,'Falcons Home | Atlanta Falcons – atlantafalcons.com','The official source of the latest Falcons headlines, news, videos, photos, tickets, NFL Draft, rosters, stats, schedule, and gameday information','','http://www.atlantafalcons.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(16,'Wikitravel - The Free Travel Guide','Open source travel guide featuring up-to-date information on attractions hotels restaurants travel tips and more.  Free and reliable advice written by Wikitravellers from around the globe.','wikitravel,wiki,travel,tourism,travel guide,hotels,restaurants,nightlife,things to do','http://wikitravel.org');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(17,'Canadian Deals, Flyers & Coupons - RedFlagDeals.com','Helping Canadians save money by viewing sales, coupons, promotions and freebies from hundreds of stores in one place!','Canadian store, deals, coupons, sales, promotions, redflagdeals, rfd','http://www.redflagdeals.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(18,'SiriusXM: Everything You Want to Hear Lives Here','Whether it’s new hip-hop and classic comedy or ‘90s jams and sports podcasts, everything you want to hear lives here at SiriusXM.','','http://www.sirius.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(19,'Raja29 | Daftar Situs Slot Online dan Judi Slot Gacor Terpercaya di Indonesia','Raja29 merupakan daftar situs slot resmi online dan judi slot gacor terbukti gampang menang dan terpercaya di indonesia.','raja29, judi online, slot online, slot gacor, judi online24jam, slot online terpercaya, slot gacor 2022, judi, situs slot, daftar slot.','http://www.lyricsdir.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(20,'
			Cele|bitchy | escapism can be smart		','Celebitchy is a daily gossip and entertainment blog, started in 2006, which also focuses on liberal politics, royal coverage and fashion.','celebitchy, celebrity, celebrities, famous, royals, royal, liberal politics, oscar, blog, gossip, pop culture, post, bitchy, entertainment, humor, photo, pictures','http://www.celebitchy.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(21,'Targeted Press Release Distribution and Professional Press Release Writing Services since 1983 | Send2Press Newswire','Targeted Press Release Distribution and Professional Press Release Writing Services since 1983 from Send2Press Newswire, a service of Neotrope. Member BBB; Inc 5000 in 2009. Accredited staff including PRSA members. Located in Temecula, Calif., USA.','press release services, press release distribution, news writing, newswire service, dissemination, distribution service, online pr, Send2Press Newswire','http://www.send2press.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(22,'College Football News','','2016 recruiting, 2016 nfl draft, vault cfn archives, greatest games, video, 2023 nfl draft, 2021 recruiting, featured posts, podcast, who's hot & who's not, tuesday question, ask cfn, transfer portal, las vegas raiders, arizona cardinals, cincinnati bengals, miami dolphins, seattle seahawks, san francisco 49ers, atlanta falcons','http://www.collegefootballnews.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(23,'ESPN: Serving sports fans. Anytime. Anywhere.','Visit ESPN to get up-to-the-minute sports news coverage, scores, highlights and commentary for NFL, MLB, NBA, College Football, NCAA Basketball and more.','ESPN, sports scores, sports news, football scores, cricket scores, rugby scores, f1 scores, golf scores, tennis scores, MLB scores, NFL scores, NBA scores, NHL scores, College Football scores, College Basketball scores, sports videos, sports information, Fantasy sports, Fantasy games, Fantasy football, Fantasy baseball','http://sports.espn.go.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(24,'UK Home | Daily Mail Online','MailOnline - get the latest breaking news, showbiz & celebrity photos, sport news & rumours, viral videos and top stories from MailOnline, Daily Mail and Mail on Sunday newspapers.','Sudoku, horoscopes, political analysis, news, Dont Miss, pictures, comment, Daily Mail, Mail on Sunday newspapers, sport, Westminster, opinion','http://www.dailymail.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(25,'Tattoos by Captain Bret & Celtic Tattoo, All styles of Custom Tattoos, Newport, RI','Tattoos by Captain Bret & Celtic Tattoo. All styles of Custom Tattoos. Newport, RI','Celtic & Custom Tradditional Tattooing, Tattoos,Tattoo, Nautical, Ladies Fine Line, Watercolors, lettering, Calligraphy, Black & Grey, colorful designs, Traditional, Tattooing, Sailor Jerry. Tribal, Polynesian, Hawaiian,coverups,repairs, Newport, Rhode Island, RI, tattoo studio, tattoo shop','http://www.tribal-celtic-tattoo.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(26,'Home | Tifton-Tift County Tourism Association','Home | A city with continuous entertainment and a huge dose of southern hospitality. Our history, culture, recreation, and progressive spirit are what make us special.','','http://www.tiftontourism.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(27,'Recipes, DIY, Home Decor & Crafts','From tried-and-true recipes and DIY crafts to home decor tips and holiday party planning, let Martha Stewart inspire you every day.','People, Fashion, Lifestyle, Entertainment, Cooking','http://www.marthastewart.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(28,'MedicineNet - Health and Medical Information Produced by Doctors','Read doctor-produced health and medical information written for you to make informed decisions about your health concerns.','medical information, symptoms and signs, disease, medical dictionary, drug information, prescription medications and drug side effects, food and drug interactions, diseases and conditions, procedures and tests, health information, medical definitions and terms, womens health, mens health, senior health','http://www.medicinenet.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(29,'Photo Prints, Custom Cards, and Posters | Walgreens Photo','Visit Walgreens Photo Center to shop for personalized photo prints, books, cards, posters, and other photo services. Get same day photo printing.','','http://photo.walgreens.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(30,'Air Charter Bahamas - Private Air Charter Flights to the Beautiful Bahamas','Air Charter Bahamas in Nassau, Bahamas is an aircraft charter service and air charter company, Providing Executive air charter service, and air charter travel.','private air charter flight,private flights to the bahamas,charter flight, marsh harbour,harbour island,executive air charter,aircraft charter,private aircraft charter,harbour island,north eleuthera,nassau,freeport,abaco islands,exumas,long island,Spanish Cay,Treasure Cay,Andros Island,Andros Town,San Andros,Chub Cay,Great Harbour Cay,Bimini,South Bimini,Cat Island, exuma, turks and caicos, providenciales, haiti, governors harbour, gaeorgetown exuma','http://www.aircharterbahamas.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(31,'Texas Lottery | Home','Texas Lottery - Play the Games of Texas!','Texas Lottery, Powerball, Mega Millions, Lotto Texas, Texas Two Step, All or Nothing, Cash Five, Pick 3, Daily 4, Scratch Tickets','http://www.txlottery.org');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(32,'The Abaco islands vacation guide, resorts, rental homes, beaches and maps directory','','','http://www.go-abacos.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(33,'Vacations','Vacations are a great way of experiencing new parts of the world, new cultures and different food. Where do fancy going next for your vacation? How do you like to travel? Vacations','travels,vacations','http://donnasands.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(34,'Sailonline.com','Yacht ownership. Sailboat charter. discount yacht charters. crewed and bareboat sailing, charter boat ownership and charter yacht buyers. Cruising logs and seamanship for yacht charters','yacht charters, yacht charter, sailboat charters,sailboat, discount yacht charters, charter, charters, catamaran, bareboat charter, boat, cruising log, charter company, yacht ownership, crewed yacht charter, seamanship, vacation, voile, bateau, captain license, British Virgin Islands, BVI, Caribbean, charter boat, sailboat charter, charter','http://www.sailonline.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(35,'AirNav','Up-to-date airport and fuel price information for Jet-A and Avgas pilots and aviation professionals.   Free, detailed aeronautical information, FBO services, hotels, and car rentals for online assistance in flight planning.','airport, FBO, fixed base operator, navigation, communications, airport data, aeronautical data, flight plan, flight planning, fixes, airways, route planning, fuel stops, cross-country, pilot','http://www.airnav.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(36,'Aircraft Specialties Services: Machining Services, Aircraft Parts and Pilot Supplies','Aircraft Specialties Services is a Part 145 Repair Station specializing in reconditioning and machining crankshafts, camshafts, tappet bodies and connecting rods. We supply new and used aircraft parts to aircraft owners, mechanics, FBO’s and engine shops through our retail outlets. PMA new parts are manufactured for certain engine models.  ',' FAA 145 Repair Station,FAA Repair Station,EASA Repair Station,8130 Certificate,Machine Shop,Airplane Machine shop, Aircraft Parts,Airplane parts,airplane engine parts,airplane engine replacement parts,aircraft engine parts, aircraft engine replacement parts,PMA Parts, Continental starter adaptor overhaul,starter adaptor overhaul,starter adaptor spring,cylinders,Overhaul,Grinding,Centerless grinding,PMA,Millennium cylinder,Titan cylinder,Plating,Nitriding,Tappets,Tappet Bodies, Lifter,Hydraulic assembly,crankshaft,TCM,STC,C-85,A-75,O-200,Piston, Accessories, AN Fittings, Battery, Brakes, Camshaft, Charts,Chemicals, Clamps, Ducting, Electrical, ELT, PLB, Engine Baffles, Fasteners, Grease, Hardware, Hoses, Lighting,Continental Motors, Connector Arms, Rocker Arms, Crankshaft, Engine Components, Engine Parts, Filters, Pilot Supplies, Flight Training Aids, Knee Boards, Log Books, Lycoming, Mags, Harnesses, Mounts, Oil, Additives, Oil Coolers, Oil Filters, Paint, Safety Wire, Sealants, Spark Plugs, Starters, Tires, Tools, Vacuum Pumps, Superior distributor, Superior air parts distributor , Bushings, Bearings, Camshafts, Crankshafts, Gaskets, O-Rings, Seals, Gears, Nuts, Bolts, Screws, Lifters, Pistons, Rings, Ring Sets, Starter Adapter Clutch springs,Valvetrain parts, Reconditioned, Refurbished, Used, Reconditioned Camshaft, Reconditioned Crankshaft, Refurbished Camshaft, Refurbished Crankshaft, Used Camshaft,Used Crankshaft,New Surplus,New Old Stock,Camguard, Overhaul Parts List','http://www.aircraft-specialties.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(37,'Stock Photography - Search 74.8 million Stock Photos, Stock Footage Video Clips, Royalty Free Images, and Illustrations','Fotosearch Stock Photography and Stock Footage helps you find the perfect photo or footage, fast! We feature 74,900,000 royalty free photos,  stock footage clips, digital videos, vector clip art images, clipart pictures, background graphics, medical illustrations, and maps.','stock photography, stock footage, stock photos, stock photo, royalty free, stock images, stock image, illustrations, illustration, clip art, clipart, pictures','http://www.fotosearch.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(38,'mg游戏app-mg摆脱辅助大神官方网站','mg游戏app汇集了最新最全的各类游戏,为您提供mg摆脱辅助大神官方网站愉悦,mg游戏app各类游戏玩法、攻略我们拥有多款火爆热门游戏,倾力打造最强在线游戏品牌!','mg游戏app,mg摆脱辅助大神官方网站','http://www.bentleytropicals.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(39,'
            
                
                    Proud Supporter Of You |
                
                Sealy
            
        ','When it comes to personalized comfort– weve got your back. We make beds to satisfy your individual needs and preferences with responsive springs, conforming foams, and best-in-class hybrids.','sealy, sealy mattress, sealy posturepedic, sealy hybrid, sealy coporation, sealy hybrid mattress, sealy mattresses, sealy posturepedic mattress, seally, sealy posturepedic mattress, sealy posturepedic queen, sealy usa, sealy beds, sealy delivery, sealy online mattress, sealy mattress in a box, sealy bed in a box, sealy express, best rated mattress, top mattress, top rated mattress','http://www.sealy.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(40,'Arkansas State Board of Nursing Arkansas Department of Health','default','default','http://www.arsbn.org');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(41,'FloridaSmart - the Smart way to find everything Florida','FloridaSmart.com is the Florida community connecting businesses, organizations and people to the information they are seeking through innovation that captures Floridas culture by putting the content the the hands of Floridians who share their stories, expertise and happenings in the state. Authentic and relevant first hand knowledge from those who live and love Florida.','Florida, Florida business, Florida schools, All about Florida','http://www.floridasmart.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(42,'Yahoo | Mail, Weather, Search, Politics, News, Finance, Sports & Videos','Latest news coverage, email, free stock quotes, live scores and video are just the beginning. Discover more every day at Yahoo!','yahoo, yahoo home page, yahoo homepage, yahoo search, yahoo mail, yahoo messenger, yahoo games, news, finance, sport, entertainment','http://www.geocities.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(43,'Colts Manufacturing LLC','Colts Manufacturing Company - firearms, handguns, pistols, rifles, revolvers.','Colt firearms,Colt pistols,Colt revolvers,Colt handguns,Colt guns,Colt Mfg,Colt Manufacturing,Colts','http://www.colt.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(44,'Mickey Thompson | Home','Mickey Thompson Tires & Wheels – UNDISPUTED.','','http://www.mickeythompsontires.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(45,'
	Home | Automotive Management Institute
','AMi is a 501(c)(3) nonprofit organization that provides industry-recognized professional management designations, and certificates.','automotive management institute ','http://www.amionline.org');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(46,'The New York Times - Breaking News, US News, World News and Videos','Live news, investigations, opinion, photos and video by the journalists of The New York Times from more than 150 countries around the world. Subscribe for coverage of U.S. and international news, politics, business, technology, science, health, arts, sports and more.','news, live updates, latest news, breaking news, local news, current events, top stories, livestream, live video, world news, us news','http://query.nytimes.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(47,'Daily Southtown News - Chicago Tribune','Daily Southtown: Your source for south and southwest Chicago suburbs news, events, crime reports, community announcements, photos, high school sports and school district news.','','http://www.dailysouthtown.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(48,'JASPER remanufactured engines, transmissions & differentials','JASPER provides remanufactured gas engines, diesel engines, marine engines, transmissions and more for your car, truck or boat.','remanufactured engines, transmissions, differentials, marine products','http://www.jasperengines.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(49,'Welcome to Taurus USA','Welcome to Taurus®. This is where innovation lives. Where rugged craftsmanship meets next generation design and engineering. uncompromising ingenuity','Taurus Firearms, Taurus Pistols, Taurus Revolvers, Taurus G3, Taurus G2, Taurus Raging Hunter,','http://www.taurususa.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(50,'Yokohama Tire | Find New Tires for Cars, SUVs And Trucks','Find the perfect tire for you. Yokohama Tire offers the ultimate in performance from all-terrain off-road tires, to high-performance track tires, to…','yokohama,yokohama tire,yokohama tires,track tires,all-terrain,off-road tires,high-performance track tires,all-season tires,automotive tires,tire dealer,tire dealers,commercial tires,tires','http://www.yokohamatire.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(51,'beloitdailynews.com | The Statelines Choice','','beloit daily news','http://www.communityshoppers.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(52,'TatSupplyCo','TatSupplyCo :  - Gloves Barrier Products Disinfection Sterilization Tattoo Machines Clipcords Tattoo Needles Tattoo Tubes Piercing Jewelry Piercing Supplies Piercing Instruments Medical Supplies Trays, Jars & Scalpels Set-Up Supplies Shop Supplies Fusion Ink Eternal Ink After Care Products Closeout Items TATSupplyCo. Apparel Soaps Gift Certificates Talen's Ink Dermal Ink Deals SUK-IT-UP Rinse Cup Solidifier Industry Inks Mentor Pro Cartridge Needles GLOVE DEALS NEEDLE & TUBE CLEARANCE ecommerce, open source, shop, online shopping, store','Gloves Barrier Products Disinfection Sterilization Tattoo Machines Clipcords Tattoo Needles Tattoo Tubes Piercing Jewelry Piercing Supplies Piercing Instruments Medical Supplies Trays, Jars & Scalpels Set-Up Supplies Shop Supplies Fusion Ink Eternal Ink After Care Products Closeout Items TATSupplyCo. Apparel Soaps Gift Certificates Talen's Ink Dermal Ink Deals SUK-IT-UP Rinse Cup Solidifier Industry Inks Mentor Pro Cartridge Needles GLOVE DEALS NEEDLE & TUBE CLEARANCE ecommerce, open source, shop, online shopping, store ','http://www.tattooshow.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(53,'Yahoo | Mail, Weather, Search, Politics, News, Finance, Sports & Videos','Latest news coverage, email, free stock quotes, live scores and video are just the beginning. Discover more every day at Yahoo!','yahoo, yahoo home page, yahoo homepage, yahoo search, yahoo mail, yahoo messenger, yahoo games, news, finance, sport, entertainment','http://www.yahoo.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(54,'Hotels & Resorts | Book your Hotel directly with Marriott Bonvoy','Browse Marriott Internationals portfolio of hotels & discover what makes each brand unique. Take the stress out of travel & book your hotel reservation direct.','Marriott','http://www.starwoodhotels.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(55,'Home Staging Workshops & Seminars : Home Staging Expert®','Home Staging Expert® is a company dedicated to to bringing you professional home staging training, seminars and workshops. Our HSE Certification is an industry-wide standard in home staging.  We offer workshops and seminars throughout the United States and Canada.','home staging, staging, home staging training, staging training, home staging workshop, staging workshop, home staging course, staging course, interior design, interior redesign, staging a home for sale','http://www.centerstagehome.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(56,'Las Cruces, NM | Official Website','','Home,city of las cruces,las cruces,utilities,roadrunner,transit,building permits,economic development,Human resources,pay my bill,city manager,codes,branigan library,public works,las cruces police department,las cruces fire department,las cruces transit,las cruces utitilies,las cruces gas company,las cruces city council','http://www.las-cruces.org');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(57,'Chicago Tribune: Chicago news, sports, weather, entertainment','Chicago Tribune: Your source for Chicago breaking news, sports, business, entertainment, weather and traffic','','http://www.chicagotribune.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(58,'
	Business for Sale - Find Great Businesses for Sale at Business Broker Network - Buy or Sell a Business
','Business for Sale Search. Great Selection of Businesses for Sale, Franchise Opportunities, and Business Brokers. New Listings Posted Daily! Sell Your Business - Post Your Own Ad!','business for sale, businesses for sale, sell a business, business brokers, business broker, selling a business, franchise, franchise, franchise opportunities, franchises, business brokerage, sell my business, franchise for sale, sell my business, buy a business, united states, USA, Canada','http://www.businessbroker.net');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(59,'Palos Heights, IL | Official Website','','Home','http://www.palosheights.org');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(60,'Local Weather Forecast, News and Conditions | Weather Underground','Weather Underground provides local & long-range weather forecasts, weather reports, maps & tropical weather conditions for locations worldwide','','http://www.wunderground.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(61,'Home | Dexter Axle Co ','Dexter is a trusted brand serving the utility trailer, recreational vehicle, marine, agricultural, and specialty markets.| Dexter Axle Co.','Home Page Keywords','http://www.ufpnet.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(62,'Dultmeier.com | Car Wash Supplies, Ag Sprayer Parts, Equipment, Pumps','Wholesale Prices on Car Wash Supplies, Ag Sprayer Parts, Spray Nozzles, Fertilizer Pumps, Valves, Poly Tanks, Deicing & Petroleum Equipment, Mobile Cleaning, Industrial Supply, Lawn/Turf/Golf Course Maintenance & Much More!','','http://www.dultmeier.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(63,'Business - For Sale Ads - Classifieds - Online Marketplace','Business - For Sale Classified Ads - Online Marketplace at BUSINESS NATION ® List Businesses for Sale, Commercial Buildings, Commercial Vehicles, Used Equipment, Website Apps & Websites for Sale Ads, Patent Listings, Biz for Sale Listing Marketplace at BusinessNation','Business for Sale Classified Ads, Opportunities, Commercial Real Estate, Online Marketplace, Ad, Properties for Sale, Office Space for Rent, Lease, Land, Farms, Commercial Vehicles, Used Equipment, Business Services, List Biz for Sale, Find Business Opportunities, Buy or Sell Franchise, Patents, Franchises, Web Sites for Sale Ads, Website Apps, Patent Listing, Biz Opportunity Listings, Liens & Notes, Water Rights, Mining, Oil & Gas Rights, Public & Private Shells, Liquor Licenses, Loan & Financing Offers, Web Site App, Patent, Startup, Start-up, Resources, BusinessNation','http://www.businessnation.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(64,'Web Page Under Construction','Network Solutions - Original domain name registration and reservation services with variety of internet-related business offerings. Quick, dependable and reliable.','domain name, domain names, domain name registration, whois, internic, dot com people, web address, TLD, .com, .net, .org, web forwarding, mail, registry, registrar, internet address, ICANN,web site, secure','http://www.drkomputing.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(65,'Government Contracts - Money, Defense Department, Federal Government Contracts','Government Contracts,Defense Contracts,United States Government Contract Awards,Federal Business,Federal Government Contracts,Weapons Systems,Products,Services,Claimant Program','Government Contracts,Defense Contracts,United States Government Contract Awards,Federal Business,Federal Government Contracts,Weapons Systems,Products,Services,Claimant Program','http://www.governmentcontractswon.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(66,'
	
    Village of Orland Park, IL | Home

','','','http://www.orland-park.il.us');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(67,'Welcome to NYC.gov | City of New York','The official website of the City of New York. Find information about important alerts, 311 services, news, programs, events, government employment, the office of the Mayor and elected officials.','','http://www.nyc.gov');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(68,'Tech Law Journal Home Page.','Tech Law Journal Home Page: news, documents, and analysis about legislation, 
regulation, and litigation affecting the computer and Internet industry.','Tech, Law, Journal, home, page, computer, internet, industry, legislation, 
litigation, regulation, Washington, DC, news, stories, coverage, article','http://www.techlawjournal.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(69,'Stevens Marine - With Locations in Tigard and Milwaukee, OR - Marine Dealer In Oregon - Providing Service, Parts and Financing in Portland','Stevens Marine is a Marine dealership with locations in Tigard and Portland, OR. We offer new and used boats and more. We carry the latest models as well as parts, service and financing for Alumaweld, Smokercraft, Kingfisher, Mercury Marine, Sunchaser  . We serve the areas of Beaverton, Portland, Milwaukee, Chehalis , and Salem ','Stevens Marine, Marine, Tigard, Portland, Oregon, OR, new, used, pre-owned, boats, parts, service, financing, Beaverton, Milwaukee, Chehalis , Salem , Alumaweld, Smokercraft, Kingfisher, Mercury Marine ','http://www.stevensmarine.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(70,'Yellow Pages | YellowPageCity.com','National network of local yellow pages. Search in communities by category, business name, products, brands or services.','yellow pages, US yellow pages, United States yellow pages, online yellow pages, local yellow pages, business listings, business listing, phone book','http://www.yellowpagecity.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(71,'Southern Illinois News & Publishing | The Southern','Southern Illinois' source for local news, business, prep sports, SIU Salukis, jobs, real estate and local advertising. Carbondale, Marion and surrounding areas.','southern Illinois news, Illinois state news, business, southern illinois entertainment, employment, local classifieds, local events, southern illinois obituaries, contests, SIU Salukis, prep sports, carbondale il news, marion il news','http://www.southernillinoisan.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(72,'Southern Illinois News & Publishing | The Southern','Southern Illinois' source for local news, business, prep sports, SIU Salukis, jobs, real estate and local advertising. Carbondale, Marion and surrounding areas.','southern Illinois news, Illinois state news, business, southern illinois entertainment, employment, local classifieds, local events, southern illinois obituaries, contests, SIU Salukis, prep sports, carbondale il news, marion il news','http://www.thesouthern.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(73,'
					Apple Chevrolet in TINLEY PARK, IL | Serving Orland Park, Chicagoland, & Rich Township Chevrolet Customers
				','Looking for dealers near Orland Park? Stop by Apple Chevrolet in TINLEY PARK, IL to find your next new car, truck, or SUV.  Stop by today. You can also check out our auto body shop in TINLEY PARK near Orland Park.','chevrolet tinley park, chevy dealership near me, used chevys for sale, orland park chevrolet dealer, chevy service center ner me, chevy service specials ','http://applechevy.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(74,'ais-sim - Belajar Dasar Permainan Judi Online','belajar bermain judi online,dasar bermain judi online,dasar judi online,judi online,belajar judi online, belajar dasar judi,','judi online,poker online,dominoqq,situs judi online, poker, situs poker, poker cc, dominoqq online, judi online terpercaya,','http://www.ais-sim.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(75,'NRA Store | Official Store of the National Rifle Association Official Store of the National Rifle Association','NRAstore.com. Official store of the National Rifle Association. Shop our extensive collection of clothes, gear, accessories, tactical items, jewelry, collectibles, and more. ','NRA, store, gear, NRAstore, NRAstore.com','http://www.nrastore.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(76,'

		
		Dick Cepek Tires & Wheels
		
	',' ','','http://www.dickcepek.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(77,'Bright Sights Gun Sight Colors – gun sight paint coatings, gun sight coatings, gun sight cleaners','As your gun sight paint coatings company, we offer gun sight colors, gun sight paint coatings, gun sight coatings, gun sight coatings application kits and gun sight cleaners, including high visibility gun coatings and luminescent gun sight coatings.','Bright Sights, gun sight paint coatings company, gun sight coatings companies, gun sight colors, gun sight paint coatings, gun sight coatings, gun sight coatings application kits, gun sight cleaners, including high visibility gun coatings, luminescent gun coatings, high-visibility gun sight coatings, luminescent gun coatings, gun sight cleaner kits, gun sight coating applicators, gun sight paint brushes','http://www.brightsights.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(78,'Cruisers & Sailing Forums ','Cruisers Forum is an online forum community of cruisers from around the world!','cruisers forum, cruisers forums, cruising, sailing forum','http://www.cruisersforum.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(79,'Rolling Stone – Music, Film, TV and Political News Coverage','Get the latest Rolling Stone news with exclusive stories and pictures from Rolling Stone.','insights, announcements, music biz commentary, rs recommends lists, music biz lists, music country videos, music latin lists, music country pictures, politics pictures, tv & movies pictures, cultural commentary, (sub)culture videos, politics videos, tv & movies videos, finance, rs recommends pictures, books, smart home, expert panels, (sub)culture pictures','http://www.rollingstone.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(80,'Welcome to Far Gone Books','Far Gone Books is publisher of the legendary Wisdoms Maw, a tour-de-force that takes the reader helter-skelter into the psychedelic world of the Sixties where god-like CIA agents dispense LSD to Beat writers such as Neal Cassady and Jack Kerouac in an attempt to create a race of mind-expanded supermen.','Sixties, LSD, Kerouac, Cassady, Kesey, Hunter, Thompson, CIA, Kennedy, conspiracy, Monroe, Marilyn, drugs, psychedelic, Jack Kerouac,Neal Cassady, Hunter S. Thompson, Alfred M. Hubbard, Alfred Matthew Hubbard, Todd Fahey, Todd Brendan Fahey, Chris Hunt, Christopher Charles Hunt, Christopher Hunt','http://www.fargonebooks.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(81,'Guy Fawkes and Bonfire Night','The history about Guy Fawkes, the Gunpowder Plot, and why British people everywhere gather round bonfires every November 5th to burn effigies of Guy and watch fireworks.','guy fawkes, bonfire night, gunpowder plot, holidays, powder treason, guido fawkes, pope day, november 5, bonfirenight, 5th of november, 1605, e-cards, postcards, books, mugs, t-shirts, faulkes, faukes, fawks','http://www.bonefire.org');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(82,'Forsiden på Kongehusets nettsted  - Det norske kongehus','Her finnes informasjon om den norske kongefamilien, samt nyheter om deres offisielle virke og program. Finn også stoff om Slottet, Slottsparken, kongelige ordener og mye annet.','Kongehuset, Kongefamilien, Kongeparet, Kronprinsparet, Kongen, Dronningen, Kronprinsen, Kronprinsessen, Monarkiet, Kong Harald, Dronning Sonja, Kronprins Haakon, Kronprinsesse Mette-Marit, Prinsesse Ingrid Alexandra, Prins Sverre Magnus, Prinsesse Märtha Louise, Prinsesse Astrid, Prinsesse Ragnhild, Hoffet, Det kongelige hoff, Slottet, Det kongelige slott, Slottsparken','http://www.kongehuset.no');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(83,'Jacksonville Beach, FL | Official Website','','Home','http://www.jacksonvillebeach.org');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(84,'Want to know the truth? Verifiable information on banking, health, energy, media, war, elections, 9/11, more','Want to know the truth? Key media articles and reliable, information-packed summaries on major cover-ups for those who want to know the truth on health, banking, energy, media, elections, war, 9/11.','want,know,cover-up,9/11,energy,media,mind,control','http://www.wanttoknow.info');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(85,'Prevention.com - Health Advice, Nutrition Tips, Trusted Medical Information','Prevention is a leading provider of trustworthy health information, empowering readers with practical strategies to improve their physical, mental, and emotional well-being.','','http://www.prevention.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(86,'Slot88 Â» Situs Judi Slot Online Anti Rungkat di Indonesia','Slot88 agen resmi situs judi slot online slot88 anti rungkat, terlengkap dan terpercaya, minimum deposit hanya lima ribu rupiah bisa menang puluhan juta rupiah.','slot online, slot online terpercaya, slot gacor, slot5000, slot88, slot online pragmatic play, slot online gacor, slot online terbaik, judi slot, judi slot online, judi slot gacor, slot anti rungkat, slot anti kalah, judi online24jam, judi online24jam deposit ovo, judi online24jam terpercaya','http://www.ediets.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(87,'Celebrity Gossip, Lifestyle, Fashion & Beauty News From Female First','Keep up-to-date with the very latest celebrity news and gossip as well as the best in lifestyle, entertainment and fashion news from Female First.','Female First, FemaleFirst, Lifestyle Magazine, Celebrity Magazine, Gossip','http://www.femalefirst.co.uk');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(88,'Province of Manitoba | Home Page','','','http://www.gov.mb.ca');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(89,'Home 1 - Precision Products INC','[cms_custom_heading heading_style="style3"','Cloud Documents','http://www.precisionproductsinc.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(90,'My Food and Family Recipes','Explore a wide variety of My Food and Family recipes today. My Food and Family recipes are great for new dinner ideas, easy meal prep and so much more.','my food and family recipes','http://www.kraftfoods.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(91,'Xanga 2.0 is Here!','Xanga 2.0 is Here!','Xanga','http://www.xanga.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(92,'Arrowhead Credit Union','Arrowhead Credit Union is one of Californias fastest growing financial institutions offering our members better rates, lower fees and excellent service.','Arrowhead Credit Union | Californias Best Credit Union, Arrowhead Credit Union, Arrowhead CU, ACU, banking, finance, membership, credit union near me, credit union, best credit union','http://www.arrowheadcu.org');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(93,'Shoes, Sneakers, Boots, & Clothing + FREE SHIPPING | Zappos.com','GET FREE SHIPPING & RETURNS! We have 1000s of styles of shoes & Zappos legendary 365-day return policy + 24/7 friendly customer service. Call 1-800-92','Zappos.com, FREE Shipping, Clothing, Shoes','http://www.zappos.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(94,'Premium Domain Names at already Discounted Prices - ezshopsave.com is available for sale! Make an Offer Today.','Search premium discount domains and check out the Domain Deal of the Day.','domains, direct domains, cheap domains, buy domains','http://www.ezshopsave.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(95,'Home Theatre, Audio, Smart TV, and Small Appliances for Sale | OneCall','Upgrade your home with the latest TVs, home audio, and small appliances. ',' Samsung Smart Homes, Projectors, Smart TV, 4K TV, Blu ray players, Television, Home Theater, Home Audio, Home Networking, Home Entertainment High-end Home Theater Systems, Speakers, Digital Satellite, custom home installation, surveillance, motion sensors, Sony, Sonos, headphones, Audio Accessories, Hi-Res Audio Speaker System, headphones, speakers, home theatre, record players, laptops, tablets, computer storage, wireless networking, and kitchen appliances. ','http://www.onecall.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(96,'Finish Carpenter | Custom Mantels & Cabinet | Deck | Remodel','Finishing carpentry, crown molding & trim work by a master carpenter. Custom Fireplace Mantel & Cabinet. Deck & remodeling - California North Bay area','','http://www.altereagle.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(97,'$$ All Online Coupons - Discount Shopping and Coupon Codes','All Online Coupons features online coupons, promo offers, discount shopping sales, internet promotion codes, and promotional deals. AllOnlineCoupons.com lists thousands of online coupon codes and discount shopping promotions for hundreds of online stores, internet services and travel sites to help you save.','online coupons,coupon codes,discount,shopping,deals,promotions,travel,internet,promo codes,discounts,promos,online,coupon','http://www.allonlinecoupons.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(98,'Home Design, Decorating and Remodeling Ideas, Landscaping, Kitchen and Bathroom Design | HGTV','Let HGTV help you transform your home with pictures and inspiration for interior design, home decor, landscape design, remodeling and entertaining ideas.','','http://www.hgtv.com');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(99,'Traditional Scouting: Boy Scout Adventure Activities Boys B-P Scouts Scuba Diving Merit Badge','Traditional Scouting: Boy Scout Games Activities B-P Scouts Scuba Diving Merit Badge','Traditional Scouting: Boy Scout Games Activities B-P Scouts Scuba Diving Merit Badge','http://www.inquiry.net');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(100,'A non-commercial service in support of responsible home heating with wood - woodheat.org home','The Wood Heat Organization was formed to support the public in the responsible use of wood energy in the home. We fulfill our mandate by providing reliable information, by conducting research into wood heating-related issues and by representing the public interest in discussions of policies that affect woodburning.','woodheat, firewood, fireplaces, wood stove, wood heat, fire wood, outdoor air quality, chimneys, wett, epa, wood smoke, clean air, hearth, wood heat safety, renewable energy','http://www.woodheat.org');
INSERT INTO paginas(Id, title, description, keywords, url) VALUES(101,'ABC Home Page - ABC.com','Watch the ABC Shows online at abc.com. Get exclusive videos and free episodes.','abc tv, abc tv shows, abc tv movies, abc specials','http://abc.go.com');
